[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/admin-config"
  to = "/.netlify/functions/admin-config"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/projects/:slug"
  to = "/project.html?slug=:slug"
  status = 200

[[redirects]]
  from = "/news/:slug"
  to = "/news-post.html?slug=:slug"
  status = 200
